version: "2.3"
services:
  backend:
    build:
       context: ./search_engine
       dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./search_engine/test_index:/test_index
      - ./search_engine/data:/data
      - ./search_engine/pip_cache:/pip_host_cache

    env_file:
      - ".env"

  frontend:
    build:
      context: ./frontend_app
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    links:
      - backend
    env_file:
      - ".env"
